export const FETCH_PARTY_LIST = 'FETCH_PARTY_LIST';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const ADD_PARTY = 'ADD_PARTY';
export const RESET_SEARCH_RESULT = 'RESET_SEARCH_RESULT';
export const FETCH_PARTY_BALANCE = 'FETCH_PARTY_BALANCE';